// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFs3lL7e9b4Db34_wspRk03cs8ehy_fZA',
    appId: '1:241105662111:web:6aed48cdb75a29ebb6f2aa',
    messagingSenderId: '241105662111',
    projectId: 'school-safety-b7759',
    authDomain: 'school-safety-b7759.firebaseapp.com',
    storageBucket: 'school-safety-b7759.appspot.com',
    measurementId: 'G-816G0K919E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrFly-WJdW3w_SY3R0aOiRhA_a8vy5GeI',
    appId: '1:241105662111:android:9e2df60a78d35f0eb6f2aa',
    messagingSenderId: '241105662111',
    projectId: 'school-safety-b7759',
    storageBucket: 'school-safety-b7759.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDblUYbEGTP8wT6jd-raws9kLwNyWVNNI8',
    appId: '1:241105662111:ios:9441f5a917830f27b6f2aa',
    messagingSenderId: '241105662111',
    projectId: 'school-safety-b7759',
    storageBucket: 'school-safety-b7759.appspot.com',
    iosClientId: '241105662111-95j35hdmf58jj5rsbqvjt5gvm9lemj6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCompleteGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDblUYbEGTP8wT6jd-raws9kLwNyWVNNI8',
    appId: '1:241105662111:ios:9441f5a917830f27b6f2aa',
    messagingSenderId: '241105662111',
    projectId: 'school-safety-b7759',
    storageBucket: 'school-safety-b7759.appspot.com',
    iosClientId: '241105662111-95j35hdmf58jj5rsbqvjt5gvm9lemj6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCompleteGuide',
  );
}
